// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Product_Catalog_API.Data;

#nullable disable

namespace Product_Catalog_API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Product_Catalog_API.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Name");

                    b.HasIndex("Price");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000001"),
                            Category = "Electronics",
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-end laptop for professionals",
                            Name = "Laptop Pro 15",
                            Price = 1200m
                        },
                        new
                        {
                            Id = new Guid("00000002-0000-0000-0000-000000000002"),
                            Category = "Electronics",
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ergonomic wireless mouse",
                            Name = "Wireless Mouse",
                            Price = 25m
                        },
                        new
                        {
                            Id = new Guid("00000003-0000-0000-0000-000000000003"),
                            Category = "Electronics",
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Mechanical RGB keyboard",
                            Name = "Gaming Keyboard",
                            Price = 75m
                        },
                        new
                        {
                            Id = new Guid("00000004-0000-0000-0000-000000000004"),
                            Category = "Electronics",
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Latest smartphone with OLED display",
                            Name = "Smartphone X",
                            Price = 999m
                        },
                        new
                        {
                            Id = new Guid("00000005-0000-0000-0000-000000000005"),
                            Category = "Electronics",
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Noise-cancelling over-ear headphones",
                            Name = "Bluetooth Headphones",
                            Price = 199m
                        },
                        new
                        {
                            Id = new Guid("00000006-0000-0000-0000-000000000006"),
                            Category = "Books",
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Comprehensive guide to C#",
                            Name = "C# Programming",
                            Price = 40m
                        },
                        new
                        {
                            Id = new Guid("00000007-0000-0000-0000-000000000007"),
                            Category = "Books",
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Learn to build web APIs",
                            Name = "ASP.NET Core in Action",
                            Price = 50m
                        },
                        new
                        {
                            Id = new Guid("00000008-0000-0000-0000-000000000008"),
                            Category = "Books",
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Engaging mystery story",
                            Name = "Mystery Novel",
                            Price = 15m
                        },
                        new
                        {
                            Id = new Guid("00000009-0000-0000-0000-000000000009"),
                            Category = "Clothing",
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "100% cotton casual T-shirt",
                            Name = "Men's T-Shirt",
                            Price = 20m
                        },
                        new
                        {
                            Id = new Guid("0000000a-0000-0000-0000-00000000000a"),
                            Category = "Clothing",
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Slim fit denim jeans",
                            Name = "Women's Jeans",
                            Price = 45m
                        },
                        new
                        {
                            Id = new Guid("0000000b-0000-0000-0000-00000000000b"),
                            Category = "Home",
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Modern wooden coffee table",
                            Name = "Coffee Table",
                            Price = 120m
                        },
                        new
                        {
                            Id = new Guid("0000000c-0000-0000-0000-00000000000c"),
                            Category = "Home",
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Desk lamp with adjustable brightness",
                            Name = "LED Lamp",
                            Price = 35m
                        },
                        new
                        {
                            Id = new Guid("0000000d-0000-0000-0000-00000000000d"),
                            Category = "Sports",
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Official size football",
                            Name = "Football",
                            Price = 25m
                        },
                        new
                        {
                            Id = new Guid("0000000e-0000-0000-0000-00000000000e"),
                            Category = "Sports",
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Professional tennis racket",
                            Name = "Tennis Racket",
                            Price = 80m
                        },
                        new
                        {
                            Id = new Guid("0000000f-0000-0000-0000-00000000000f"),
                            Category = "Toys",
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Collectible action figure",
                            Name = "Action Figure",
                            Price = 25m
                        },
                        new
                        {
                            Id = new Guid("00000010-0000-0000-0000-000000000010"),
                            Category = "Toys",
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "500-piece jigsaw puzzle",
                            Name = "Puzzle Game",
                            Price = 15m
                        },
                        new
                        {
                            Id = new Guid("00000011-0000-0000-0000-000000000011"),
                            Category = "Electronics",
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "50-inch 4K Ultra HD Smart TV",
                            Name = "Smart LED TV 50\"",
                            Price = 450m
                        },
                        new
                        {
                            Id = new Guid("00000012-0000-0000-0000-000000000012"),
                            Category = "Home",
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fast boiling stainless steel kettle",
                            Name = "Electric Kettle",
                            Price = 30m
                        },
                        new
                        {
                            Id = new Guid("00000013-0000-0000-0000-000000000013"),
                            Category = "Clothing",
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lightweight breathable running shoes",
                            Name = "Running Shoes",
                            Price = 60m
                        },
                        new
                        {
                            Id = new Guid("00000014-0000-0000-0000-000000000014"),
                            Category = "Home",
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Non-stick pots and pans set",
                            Name = "Cookware Set 10pcs",
                            Price = 120m
                        },
                        new
                        {
                            Id = new Guid("00000015-0000-0000-0000-000000000015"),
                            Category = "Toys",
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fun family board game",
                            Name = "Board Game Classic",
                            Price = 35m
                        });
                });

            modelBuilder.Entity("Product_Catalog_API.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
